
(DEFSYSTEM "sb-bsd-sockets" :CLASS ASDF::PREBUILT-SYSTEM :LIB #P"SYS:SB-BSD-SOCKETS.LIB" :DEPENDS-ON ("sockets") :COMPONENTS ((:COMPILED-FILE "sb-bsd-sockets" :PATHNAME #P"SYS:SB-BSD-SOCKETS.FAS"))) 